title: Homepage
# email:
# description: >- # this means to ignore newlines until "baseurl:"

url: https://leonkang.com/
# twitter_username: jekyllrb
github_username: Leon-Kang

# Build settings
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
