# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            LK
tagline:          'What a wonderful world'
description:      'We must be strong on the way of growth.'
url:              http://Leon-Kang.github.io

author:
  name:           'Leon-Kang'
  url:            http://Leon-Kang.github.io

paginate:         5

# Custom vars
version:          1.0.0

