title: LK
email: me@ojbk.dev
description: 'We must be strong on the way of growth.'
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://leonkang.com/
github_username:  Leon-Kang

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
