# Site settings
title: What a wonderful world .
email: 376450758@qq.com
relative_permalinks: false

description: We must be strong on the way of growth .

github_username: Leon-Kang

# Build settings
markdown: kramdown
url: "http://Leon-Kang.github.io"
output: true
pygments: true
